export type NotificationType =
  /** mentor */
  | "MENTOR_RECEIVE_MENTEE_APPLY_FROM_MENTEE_FLOW"
  | "MENTOR_RECEIVE_MENTEE_CANCEL_FROM_MENTEE_FLOW"
  | "MENTOR_RECEIVE_MENTOR_APPROVE_FROM_MENTEE_FLOW"
  | "MENTOR_RECEIVE_MENTEE_CANCEL_FROM_MENTOR_FLOW"
  | "MENTOR_RECEIVE_MENTEE_REJECT_FROM_MENTOR_FLOW"
  | "MENTOR_RECEIVE_MENTEE_PENDING_FROM_MENTOR_FLOW"
  | "MENTOR_RECEIVE_MENTOR_FINALLY_APPROVE_FROM_MENTOR_FLOW"

  /** mentee */
  | "MENTEE_RECEIVE_MENTOR_CANCEL_FROM_MENTEE_FLOW"
  | "MENTEE_RECEIVE_MENTOR_REJECT_FROM_MENTEE_FLOW"
  | "MENTEE_RECEIVE_MENTOR_APPROVE_FROM_MENTEE_FLOW"
  | "MENTEE_RECEIVE_MENTOR_SUGGEST_FROM_MENTOR_FLOW"
  | "MENTEE_RECEIVE_MENTOR_CANCEL_FROM_MENTOR_FLOW"
  | "MENTEE_RECEIVE_MENTOR_FINALLY_CANCEL_FROM_MENTOR_FLOW"
  | "MENTEE_RECEIVE_MENTOR_FINALLY_APPROVE_FROM_MENTOR_FLOW";
