export type NotificationType =
  /** mentor */
  | "MENTOR_RECEIVE_MENTEE_FLOW_MENTEE_APPLY"
  | "MENTOR_RECEIVE_MENTEE_FLOW_MENTEE_CANCEL"
  | "MENTOR_RECEIVE_MENTEE_FLOW_MENTOR_APPROVE"
  | "MENTOR_RECEIVE_MENTOR_FLOW_MENTEE_CANCEL"
  | "MENTOR_RECEIVE_MENTOR_FLOW_MENTEE_REJECT"
  | "MENTOR_RECEIVE_MENTOR_FLOW_MENTEE_PENDING"
  | "MENTOR_RECEIVE_MENTOR_FLOW_MENTOR_FINALLY_APPROVE"
  /** mentee */
  | "MENTEE_RECEIVE_MENTEE_FLOW_MENTOR_CANCEL"
  | "MENTEE_RECEIVE_MENTEE_FLOW_MENTOR_REJECT"
  | "MENTEE_RECEIVE_MENTEE_FLOW_MENTOR_APPROVE"
  | "MENTEE_RECEIVE_MENTOR_FLOW_MENTOR_SUGGEST"
  | "MENTEE_RECEIVE_MENTOR_FLOW_MENTOR_CANCEL"
  | "MENTEE_RECEIVE_MENTOR_FLOW_MENTOR_FINALLY_CANCEL"
  | "MENTEE_RECEIVE_MENTOR_FLOW_MENTOR_FINALLY_APPROVE";
